### ISSUE TITLE
기능 구현 더 남은거 

### ISSUE THREAD

**Issue by Kim-Dong-Jun99** [vivi108/MobileTerm#127]
그 그룹 스케줄 스터디에서 보면은 그 스터디 스케줄만 보이게 하고 그냥 캘린더 들어가서 보면, 개인의 전체 그룹 스케줄이 보이게 

그리고 지역 기반으로 오프라인 스터디 검색가능하게 하고 보여주기

**Comment by Kim-Dong-Jun99** [comment]
태그 검색후 스터디 누르면 에러남

**Comment by Kim-Dong-Jun99** [comment]
공유 캘린더 눌렀을때 일정 생성할건지, 아님 공유 캘린더를 보여주는거 구현해야함

**Comment by Kim-Dong-Jun99** [comment]
캘린더 전환 라디오 버튼 더블 클릭해야함

**Comment by Kim-Dong-Jun99** [comment]
별점 삭제하고 스터디 게시물 좋아요수만 보이게 관심 x

**Comment by Kim-Dong-Jun99** [comment]
스터디 프레그멘트에서 최대인원수랑, 현재 인원수 보여주기,

**Comment by Owen-Choi** [comment]
응원합니당

**Comment by Kim-Dong-Jun99** [comment]
스터디 게시글에서 좋아요수 보이게 그리고 스터디 게시글 생성이랑 리스트뷰 xml 정리
