### ISSUE TITLE
게시판 끝난 줄 알았는데,,,,,,,

### ISSUE THREAD

**Issue by Kim-Dong-Jun99** [vivi108/MobileTerm#81]
아니ㅇ였음, 그 메소드를 통일해야할듯, 지금 보면 태그 지우기, 검색 버튼 눌렀을때, 검색 눌렀을때, 다 실행되는 메소드가 다름

메소드를 하나로 통일해서 해줘야할 듯

버튼들 눌렀을때 어댑터에서 처리해줘야하는 부분 - > searchEditText, tagSearchEditText, radioGroup

**Comment by Owen-Choi** [comment]
(대충 응원한다는 뜻)

**Comment by Kim-Dong-Jun99** [comment]
음 게시판을 지금 보면 태그 검색 하려면 쿼리 날려야함, 그냥 검색은 안해도된다, 그럼 케이스 분류해서 하면 될듯?

search == 0 & tag == 0

serach > 0 & tag == 0

search = 0 & tag == 0

search >0 & tag > 0
